- name: remove existing directory
  tags:
  - deployement
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"  # backend folder is /app and front end is /usr/share/nginx/html
    state: absent

- name: create app directory
  tags:
  - deployement
  ansible.builtin.file:
       path: "{{ APP_LOCATION }}"  # backend folder is /app and front end is /usr/share/nginx/html
       state: directory

- name: download app code
  tags:
  - deployement
  ansible.builtin.unarchive:
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ COMPONENT }}-v2.zip"
    dest: "{{ APP_LOCATION }}" 
    remote_src: yes
